name: deploy
on: [push]
jobs:
  build-to-gh-pages:ß
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm i -g gh-pages
      - run: npm i
      - run: npm run build
      - run: gh-pages -d dist