name: deploy
on: [push]
jobs:
  build-to-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm i push-dir -D
      - run: npm i
      - run: npm run build
      - run: git config --global user.email "jdog.derr1108@gmail.com"
      - run: git config --global user.name "jonathonderr"
      - run: push-dir --dir=dist --branch=gh-pages