name: deploy
on: [push]
jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master

    - name: Use Node.js
      uses: actions/setup-node@v1

    - name: npm install and build
      run: |
        npm i
        npm run build

    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: git@github.com:jonathonderr/jonathonderr.github.io.git
        BRANCH: gh-pages
        FOLDER: dist
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }} 
  generate-rss-feed:
    name: Generates RSS Feed
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master

    - name: Create File
      run:
        cd public/files && touch file.txt